import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider/QueryProvider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="navbar bg-base-100">
            <div className="flex-1">
              <Link href="/post" className="btn btn-ghost text-xl">
                Posts
              </Link>
            </div>
          </div>
          <div className="flex w-full">
            <div className="flex flex-wrap justify-center items-center w-full">
              {children}
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
